spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc.lob.non_contextual_creation: true
  h2:
    console:
      enabled: true # http://localhost:8080/h2-console/
  profiles:
    include: oauth

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
